# Format for logging output.
# See https://docs.python.org/2/library/logging.html#logrecord-attributes
# Type: str
log_format: "%(asctime)-15s\t%(levelname)s\t%(message)s"

# Number of worker processes to fork for receving requests. This option
# is mutually exclusive with debug.
# Type: int
num_processes: 1

# The port to listen to requests on.
# Type: int
port: 8990

# The address to bind to. By default it listens on all interfaces.
# Type: string
bind_address: "127.0.0.1"

# Passing debug option down tornado. Useful for development to
# automatically reload code.
# Type: bool
debug: true

# Takes a SqlAlchemy URL to the database. More details
# can be found at the following URL:
# http://docs.sqlalchemy.org/en/rel_0_9/core/engines.html#database-urls
#
# Type: str
database: "sqlite:///nsot.sqlite"

# Header to check for Authenticated Email
# Type: str
user_auth_header: "X-NSoT-Email"

# Allows you to restrict requests to certain IP addresses and/or IP networks
# specified in CIDR notation.
# Type: str or list
restrict_networks: "127.0.0.1"

# Specifies whether to use XSRF headers/cookies for API calls. Default: true
# Type: bool
api_xsrf_enabled: false

# Secret key used to encrypt/decrypt your secure cookies and API auth_tokens.
# This MUST be a URL-safe base64-encoded 32-byte key. This must be kept secret.
# Anyone with this key is able to create and read messages.
# Type: str
secret_key: "AzYHE3xqJyCykjFPYDt-iNapZEU7sxqfnXvtzG7Ddeg="

# This is the expiration (in seconds) of auth_tokens used for API calls
# Type: int
auth_token_expiry: 600

# This is a Sentry-compatible DSN for sending tracebacks to Sentry. If set, any
# errors will be sent to the specified Sentry DSN URI. For this to work you
# must also have the `python-raven` client installed. You may install it using
# # `pip install raven`.
#
# See: http://raven.readthedocs.org/en/latest/config/index.html#the-sentry-dsn
# Type: str
sentry_dsn: null
